<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{28c255d8-6965-4217-82e9-a941df42268f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbReadCoilExample : FB_ReadCoilExample;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbReadCoilExample();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>